name: Generate PSI report
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: psi-gh-action
        uses: mazipan/psi-gh-action@1.1.0
        with:
          api_key: ${{ secrets.PSI_API }}
          urls: |
            https://blog.nyandev.id/
          devices: |
            mobile
            desktop
          runs: 1
          branch: psi-result
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Bump version tag
        run: git tag ${{ github.event.inputs.version }}